### ISSUE TITLE
initial shell output discarded

### ISSUE THREAD

**Issue by peterhurley** [magit/with-editor#10]
with-editor-export-editor sets the process-filter to ignore output while injecting the process string. This discards the initial output of the shell, including motd and the shell prompt so initially the buffer is blank.

**Comment by tarsius** [comment]
Thanks for letting me know.

**Comment by tarsius** [comment]
Using `ignore` as the filter does not have the desired effect of not showing the command that is run to set `$EDITOR` when using `term`. And when using `shell` it has the undesired effect described above.
