### ISSUE TITLE
`export` output on new terminal buffers

### ISSUE THREAD

**Issue by iyefrat** [magit/with-editor#101]
Hi!
When I open new terminal buffers in `term`, `shell`, and `vterm`, with `with-editor` set up, They are opened with the inputted `export` commands that set up `$EDITOR` and `$GIT_EDITOR`. This does not happen for `eshell`, which makes sense, because from reading the source code it seems to set the environmental variables directly rather than through shell input.

Is this a bug on my end or the intended result? I think it would make more sense to clear the terminal after this input, It just feels like noise.

**Comment by tarsius** [comment]
This is a long standing issue, which I previously closed as "wontfix", but apparently without actually labeling the issue as such; I cannot find the past discussion.

However I had another look and it seems that for `shell` the export command is not actually shown. The initial prompt is duplicated, which I find acceptable, wontfix.

For `vterm` I was able to call `clear` to make the export command go away. I have just pushed that.

For `term` I could not get it to work and I will stick to wontfix for that. I would accept a pull-request that addresses this reliably though.

**Comment by iyefrat** [comment]
Thanks! 

Not sure why, but for me on `emacs -Q` I do get the export commands on `shell`, maybe it's Emacs 28? At any rate a wontfix is a wontfix. Personally I use `vterm` and `eshell`, but I want to PR `with-editor` integration into Doom Emacs, so I'll probably just only add it for the `eshell` and `vterm` modules then.
