### ISSUE TITLE
shell-commands not seeing $EDITOR override

### ISSUE THREAD

**Issue by dpassen** [magit/with-editor#116]
I use with-editor alongside vterm and see my `$EDITOR` variable set appropriately to an invocation of emacsclient.

However, when I use either `with-editor-shell-command` or `with-editor-async-shell-command`, I do not. I've tried `echo $EDITOR` as well as `env` as the shell command and both confirm to me that `$EDITOR` is not being set properly.

with-editor 20220810.1159
emacs 28.2
macOS Ventura 13.0

If there's more detail I can provide, please let me know. Thank you.

**Comment by tarsius** [comment]
I don't know why it doesn't work for you. I recommend you add a debug statement to `with-editor-async-shell-command`, something like `(message "EDITOR: %s" (getenv "EDITOR")`, inside `with-editor`. If that doesn't reveal anything, then also add debug statements to that macro and make sure you evaluate both the macro and the command before trying again.

**Comment by tarsius** [comment]
`with-editor-async-shell-command` works by binding `EDITOR` and then relying on nothing else changing the value again. If your `.zshrc` changes it, then you will have to find a way to prevent that. The `INSIDE_EMACS` envvar might help with that or check if you are using a "dumb shell", which is the case here I believe.

**Comment by dpassen** [comment]
Thanks for your help, it appears exporting editor like this:
```sh
export EDITOR="${EDITOR:-mg}"
```
solves my issues.

**Comment by tarsius** [comment]
You are welcome!

(If added the `faq` label, so that I might one day document that somewhere.)
