### ISSUE TITLE
homebrew emacs-plus breaks with-editor--setup

### ISSUE THREAD

**Issue by ag91** [magit/with-editor#119]
Thanks a lot for this little utility. I discovered that my password manager (password-store.el) uses it and breaks on MacOS.
The formula I use emacs-plus, saves the emacs-client executable in a directory looking like */emacs-plus@28.8/28.8/bin.

Now in with-editor--setup on line 511, you have `(shell-quote-argument with-editor-emacsclient-executable)`, and if you run it on my path:

`(shell-quote-argument "/opt/homebrew/Cellar/emacs-plus@28/28.2/bin/emacsclient")`
you get 

"/opt/homebrew/Cellar/emacs-plus\\@28/28.2/bin/emacsclient"

that back slash before @ is very bad because then the terminal cannot find emacsclient!

I would have opened a PR but I am not sure if there was a good reason to shell-quote-argument the client path? Any chance you can help?

**Comment by tarsius** [comment]
> I would have opened a PR but I am not sure if there was a good reason to shell-quote-argument the client path?

There might be spaces in the path.

> that back slash before @ is very bad because then the terminal cannot find emacsclient!

The shell? A quick experiment seems to confirm that at least bash has no problems with a needlessly quoted @. `shell-quote-argument` wouldn't quotes that character if it wasn't expected that doing so is necessary in some cases and basically has no effect in other cases.

What program is having issues with the quoting? Maybe you could teach it to unquote.

**Comment by tarsius** [comment]
Maybe we have to add a kludge to `with-editor` but it could also be that it would be more appropriate to make a change elsewhere.

**Comment by tarsius** [comment]
Since the only thing the shell does is to store it in a variable for other processes to use, it doing full shell quoting might be too much. Maybe we should just:

```diff
+(shell-quote-argument with-editor-emacsclient-executable)
-(replace-regexp-in-string "\s" "\\\\\\&" with-editor-emacsclient-executable)
```

Maybe not even that is necessary. But I expect that some programs will fail if there is no quoting, while others will fail if there is quoting. Since nobody reported an issue yet with the whitespace quoting in place, the safe thing to do, is to keep it.

**Comment by tarsius** [comment]
Hm, I have to think this through again, when I have a clearer mind.

**Comment by ag91** [comment]
> What program is having issues with the quoting? Maybe you could teach it to unquote

this bit here of `pass` breaks miserably https://git.zx2c4.com/password-store/tree/src/password-store.sh#n503

I am a bit unpractical with the special character management in bash, so I found it easier to propose a solution on this side (which seems causing the error).
I will report this issue also to that side, so maybe they will suggest a resolution here.

(If you think it is too much hassle, never mind I modified the function for myself and I think it is only a zsh/MacOS problem with that particular homebrew formula)

**Comment by ag91** [comment]
thank you for solving this and happy 2023 @tarsius !

**Comment by tarsius** [comment]
I've reverted this; it wasn't the right thing to do.

See #121 for the reasoning. There, I also mention how `pass` should be fixed.

**Comment by ag91** [comment]
sorry for bothering you with the extra work. Your explanation was super interesting though, thanks for commenting that in the other issue!
