### ISSUE TITLE
EDITOR is not set correctly for it to be usable in zsh.

### ISSUE THREAD

**Issue by BernardHurley** [magit/with-editor#12]
Contrary to what many people seem to think the zsh is not backward compatible with bourne shells.  The main area of incompatiblilty is that it does not parse strings as words separated by spaces, but has another construct called an array which does do this.  Here is a simple example of how it goes wrong:

```
To take a simple example, if I do:
  ~% test="ls -l" 
  ~% $test    
zsh: command not found: ls -l
```

As you can see “ls -l” has been taken as the name of a command, not a command followed by an argument.  When I try to run a terminal with  inside emacs I get the following:

```
 12012 ~% export EDITOR=sh\ -c\ \'echo\ \"WITH-EDITOR\:\ \$\$\ OPEN\ \$0\"\;\ sleep\ 604800\ \&\ sleep\=\$\!\;\ trap\ \"kill\ \$sleep\;\ exit\ 0\"\ USR1\;\ trap\ \"kill\ \$sleep\;\ exit\ 1\"\ USR2\;\ wait\ \$sleep\'
export: EDITOR: inconsistent type for assignment
 12013 ~% echo $EDITOR
emacsclient           
 12014 ~% 
```

The basic cause is the same, namely that zsh does not parse strings the same way as other shells. Note, in particular that the value of EDITOR remains unchanged.

The simplest situation in which I get this effect ist to run:

```
emacs -Q -l tester.el
```

Where tester.el contains the following code:

```
(add-to-list 'load-path "/path/to/with-editor")
(add-to-list 'load-path "/path/to/dash")
(add-hook 'term-exec-hook   'with-editor-export-editor)
(require 'with-editor)
```

If I then do M-x ansi-term and ask it to run /bin/zsh, I get the error.

In case it is of use my emacs version is:

```
GNU Emacs 25.1.50.1 (x86_64-unknown-linux-gnu, GTK+ Version [3.14.5) of 2016-09-14
```

uname -a gives:

```
Linux snares-penguin 4.7.3-gnu #1 SMP Wed Sep 7 13:31:10 UTC 2016 x86_64 GNU/Linux
```

And I am using stumpwm window manager.

To solve the problem, EDITOR needs to be a zsh array as in:

```
export EDITOR=( sh -c 'echo "WITH-EDITOR: $$ OPEN $0"; sleep 604800 & sleep=$!; trap "kill $sleep; exit 0" USR1; trap "kill $sleep; exit 1" USR2; wait $sleep' )
```

Note that there is no way of achieving this by changing with-editor-sleeping-editor. As a temporary solution I have edited lines 549-552 of with-editor.el from:

```
(process-send-string
       process (format "export %s=%s\n" envvar
                       (shell-quote-argument with-editor-sleeping-editor)))
```

to:

```
(process-send-string
       process (format "export %s=%s\n" envvar
                       "( sh -c 'echo \"WITH-EDITOR: $$ OPEN $0\"; sleep 604800 & sleep=$!; trap \"kill $sleep; exit 0\" USR1; trap \"kill $sleep; exit 1\" USR2; wait $sleep' )"))
```

but something better is needed, especially when dealing with remote shells which may or may not be zsh.

**Comment by tarsius** [comment]
> Contrary to what many people seem to think the zsh is not backward compatible with bourne shells.

That may be so, but it seems that it can also be configured to be more or less compatible. I use zsh as an interactive shell too and for me bourne-style variable assignment works. I suspected that I have set some option in my `.zshrc` to make this works, but it turned out that even with the default `.zshrc` for my system, which is

```
# Set up the prompt

autoload -Uz promptinit
promptinit
prompt adam1

setopt histignorealldups sharehistory

# Use emacs keybindings even if our EDITOR is set to vi
bindkey -e

# Keep 1000 lines of history within the shell and save it to ~/.zsh_history:
HISTSIZE=1000
SAVEHIST=1000
HISTFILE=~/.zsh_history

# Use modern completion system
autoload -Uz compinit
compinit

zstyle ':completion:*' auto-description 'specify: %d'
zstyle ':completion:*' completer _expand _complete _correct _approximate
zstyle ':completion:*' format 'Completing %d'
zstyle ':completion:*' group-name ''
zstyle ':completion:*' menu select=2
eval "$(dircolors -b)"
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*' list-colors ''
zstyle ':completion:*' list-prompt %SAt %p: Hit TAB for more, or the character to insert%s
zstyle ':completion:*' matcher-list '' 'm:{a-z}={A-Z}' 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=* l:|=*'
zstyle ':completion:*' menu select=long
zstyle ':completion:*' select-prompt %SScrolling active: current selection at %p%s
zstyle ':completion:*' use-compctl false
zstyle ':completion:*' verbose true

zstyle ':completion:*:*:kill:*:processes' list-colors '=(#b) #([0-9]#)*=0=01;31'
zstyle ':completion:*:kill:*' command 'ps -u $USER -o pid,%cpu,tty,cputime,cmd'
```

So maybe something in there makes it work, or something in your `.zshrc` makes it not work. All I know at this point is that it *can* work.

**Comment by BernardHurley** [comment]
What I described is the official default behaviour of zsh and can only be changed by setting the option SH_WORD_SPLIT.  This is explained in the FAQ at: http://zsh.sourceforge.net/FAQ/zshfaq03.html#31

How are you calling zsh?  The man page says:

       The following options are set if the shell is invoked  as  sh  or  ksh:
       NO_BAD_PATTERN,    NO_BANG_HIST,    NO_BG_NICE,   NO_EQUALS,   NO_FUNC-
       TION_ARGZERO, GLOB_SUBST,  NO_GLOBAL_EXPORT,  NO_HUP,  INTERACTIVE_COM-
       MENTS,  KSH_ARRAYS,  NO_MULTIOS, NO_NOMATCH, NO_NOTIFY, POSIX_BUILTINS,
       NO_PROMPT_PERCENT,    RM_STAR_SILENT,    SH_FILE_EXPANSION,    SH_GLOB,
       SH_OPTION_LETTERS,   SH_WORD_SPLIT.    Additionally  the  BSD_ECHO  and
       IGNORE_BRACES options are set if zsh  is  invoked  as  sh.   Also,  the
       KSH_OPTION_PRINT,  LOCAL_OPTIONS,  PROMPT_BANG,  PROMPT_SUBST  and SIN-
       GLE_LINE_ZLE options are set if zsh is invoked as ksh.

So if you have linked /usr/bin/zsh to /usr/bin/sh and are calling it as sh, you will get the behaviour you describe.

**Comment by tarsius** [comment]
How are you calling zsh?

I call `/usr/bin/zsh` not a link named `sh`.

```
$ ls -al /usr/bin/zsh
lrwxrwxrwx 1 root root 28 Apr 17  2014 /usr/bin/zsh -> /etc/alternatives/zsh-usrbin
$ ls -al /etc/alternatives/zsh-usrbin
lrwxrwxrwx 1 root root 9 Apr 26  2015 /etc/alternatives/zsh-usrbin -> /bin/zsh5
$ ls -al /bin/zsh5
-rwxr-xr-x 1 root root 722464 Nov 25  2014 /bin/zsh5
$ ls /bin/zsh*
/bin/zsh  /bin/zsh4  /bin/zsh5
```

The value of `SH_WORD_SPLIT` appears to be `" --"`.

I don't see that variable set anywhere in `/etc/zsh/*` or `~/.zsh*`. Maybe there also is a compile time flag?

There are a few things uncertain here and I will have to investigate.

----

Anyway. I acknowledge that there is an issue here and that I have to do something about it, but I don't have the time to do so right now. Meanwhile could you please just keep using your patch or setting `SH_WORD_SPLIT`?

**Comment by tarsius** [comment]
I have decided that addressing this issue is not worth the effort, for the following reasons:

* Zsh can be configured to accept the regular bourne syntax.
* This is only in a code-path that goes beyond the original scope of the package. I only implemented that because a user managed to convince me that "this won't increase the long-time maintenance costs much".
* As you said "something better is needed, especially when dealing with remote shells which may or may not be zsh."
  * I don't like that setting the variable leaves a visible trace in the buffer.
  * So I don't want to run yet another command, this time to figure out whether zsh is used and configured in a way that makes it necessary to set the variable differently. To few users will be affected by this, I don't want to inconvenient everybody else.

 I would be willing to merge a pull request, but that would have to take part of the "somewhat better is needed" part.

**Comment by tarsius** [comment]
This is what is left of my experiments related to this:

```diff
diff --git a/with-editor.el b/with-editor.el
index 40a8363..5bc51cc 100644
--- a/with-editor.el
+++ b/with-editor.el
@@ -210,6 +210,22 @@ (defcustom with-editor-sleeping-editor "\
   :group 'with-editor
   :type 'string)
 
+(defcustom with-editor-use-zsh-array nil
+  "Whether to set shell variables using Zsh's array syntax.
+
+If the SH_WORD_SPLIT option isn't set, then Zsh does not support
+something like EDITOR=\"sh -c 'echo ...'\", which With-Editor uses
+by default.  Instead on has to use `EDITOR=(sh -c 'echo ...').
+
+If you have configured Zsh so that it only accepts the second
+form, then you should this to t.  You can also use a predicate
+function that returns a boolean, which may be useful if you use
+Zsh locally, but not on all machines you connect to using Tramp."
+  :group 'with-editor
+  :type '(choice (const :tag "on" t)
+                 (const :tag "off" nil)
+                 (function :tag "Predicate")))
+
 (defcustom with-editor-finish-query-functions nil
   "List of functions called to query before finishing session.
 
@@ -567,7 +583,9 @@ (cl-defun with-editor-export-editor (&optional (envvar "EDITOR"))
       (goto-char (process-mark process))
       (process-send-string
        process (format " export %s=%s\n" envvar
-                       (shell-quote-argument with-editor-sleeping-editor)))
+                       (if with-editor-use-zsh-array
+                           nil
+                         (shell-quote-argument with-editor-sleeping-editor))))
       (while (accept-process-output process 0.1))
       (set-process-filter process filter)
       (if (derived-mode-p 'term-mode)
```
