### ISSUE TITLE
Emacs Snap installation - unable to commit via magit

### ISSUE THREAD

**Issue by SreenivasVRao** [magit/with-editor#125]
When trying to commit changes with `(magit-commit)`

I see the following error:
```
  1 git --no-pager --literal-pathspecs -c core.preloadindex\=true -c log.showSignature\=false -c color.ui\=false -c color.diff\=false commit --
hint: Waiting for your editor to close the file...
/usr/local/bin/emacsclient --socket-name=/run/user/1000/emacs/server: 1: /usr/local/bin/emacsclient: not found

```

toggle-debug-on-error returned no issues.

Output of `which`: 

```
sreenivas@arceus:~/.doom.d$ which emacs
/snap/bin/emacs
sreenivas@arceus:~/.doom.d$ which emacsclient
/snap/bin/emacsclient
sreenivas@arceus:~/.doom.d$ 
```

`(with-editor-locate-emacsclient)` returns "/snap/emacs/2103/usr/bin/emacsclient"

Output of `with-editor-debug`

```
with-editor: /home/sreenivas/.config/emacs/.local/straight/build-29.0.92/with-editor/with-editor.el
emacs: /snap/emacs/2103/usr/bin/emacs (29.0.92)
system:
  system-type: gnu/linux
  system-configuration: x86_64-pc-linux-gnu
  system-configuration-options: --prefix=/snap/emacs/current/usr --with-x-toolkit=gtk3 --without-xaw3d --with-modules --with-cairo --with-native-compilation --with-xinput2 --with-tree-sitter --with-json 'CFLAGS=-isystem/build/emacs/parts/emacs/install/usr/include -isystem/build/emacs/parts/emacs/install/usr/include/x86_64-linux-gnu -isystem/build/emacs/stage/usr/include -O2' 'CPPFLAGS=-isystem/build/emacs/parts/emacs/install/usr/include -isystem/build/emacs/parts/emacs/install/usr/include/x86_64-linux-gnu -isystem/build/emacs/stage/usr/include' 'LDFLAGS=-L/build/emacs/parts/emacs/install/lib -L/build/emacs/parts/emacs/install/usr/lib -L/build/emacs/parts/emacs/install/lib/x86_64-linux-gnu -L/build/emacs/parts/emacs/install/usr/lib/x86_64-linux-gnu -L/build/emacs/stage/usr/lib'
server:
  server-running-p: t
  server-process: #<process server>
  server-use-tcp: nil
  server-name: server
  server-socket-dir: /run/user/1000/emacs
    server
  server-auth-dir: ~/.config/emacs/server/
    WARNING: not an accessible directory
with-editor-emacsclient-executable:
 value:   /usr/local/bin/emacsclient (nil)
 default: /usr/local/bin/emacsclient (nil)
 funcall: /snap/emacs/2103/usr/bin/emacsclient (29.0.92)
path:
  $PATH: "/home/sreenivas/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin:/snap/emacs/current/usr/bin"
  exec-path: (/home/sreenivas/.cargo/bin /usr/local/sbin /usr/local/bin /usr/sbin /usr/bin /sbin /bin /usr/games /usr/local/games /snap/bin /snap/bin /snap/emacs/current/usr/bin /snap/emacs/current/usr/libexec/emacs/29.0.92/x86_64-pc-linux-gnu/)
  with-editor-emacsclient-path:
    /snap/emacs/2103/usr/bin (t)
      /snap/emacs/2103/usr/bin/emacsclient (29.0.92)
    /home/sreenivas/.cargo/bin (t)
    /usr/local/sbin (t)
    /usr/local/bin (t)
    /usr/sbin (t)
    /usr/bin (t)
    /sbin (usr/sbin)
    /bin (usr/bin)
    /usr/games (t)
    /usr/local/games (t)
    /snap/bin (t)
      /snap/bin/emacs.emacsclient (29.0.92)
      /snap/bin/emacsclient (29.0.92)
    /snap/emacs/current/usr/bin (t)
      /snap/emacs/current/usr/bin/emacsclient (29.0.92)
    /snap/emacs/current/usr/libexec/emacs/29.0.92/x86_64-pc-linux-gnu/ (t)

```

**Comment by tarsius** [comment]
```
with-editor-emacsclient-executable:
 value:   /usr/local/bin/emacsclient (nil)
 default: /usr/local/bin/emacsclient (nil)
 funcall: /snap/emacs/2103/usr/bin/emacsclient (29.0.92)
```

`with-editor-emacsclient-executable` is eventually able to locate a suitable executable, just not when the value of `with-editor-emacsclient-executable` is set, which is when it counts.

- It seems weird to me that the `/snap/...` directories come at the end of you `$PATH`. Shouldn't they be searched before `/usr/bin` and other standard locations? If unsure, refer to the snap documentation (I don't use it).
- Does `/usr/local/bin/emacsclient` actually exist and is executable? Is it a symlink, and if so does it link to an existing executable?
- I am surprised by the nil in `value: /usr/local/bin/emacsclient (nil)`. Reading the source I would have expected either `value: nil (nil)` or `value: /path (version)`, but not a mixture. I'll have to investigate that.

**Comment by SreenivasVRao** [comment]
Hi Tarsius - sorry for the late response on this issue:

it seems like the missing symlink was the problem. I resolved this with:

`sudo ln -s /snap/bin/emacsclient /usr/local/bin/emacsclient`


Thanks for creating magit and transient! I use it all the time both personally and professionally! :)

**Comment by tarsius** [comment]
Do you know why the symlink was missing?

A possible reason is that, I assume, one has to symlink all executables explicitly when creating a "snap", and the person who created this snap does not use `emacsclient`, so they did not bother to do it for that executable. If this is a popular snap for Emacs, maybe even the snap that people are most likely to use, then this is a problem, because its numerous users will all encounter the same issue.

Could you please check if the problem is indeed something along those lines, and inform the maintainer of the snap about this?
