### ISSUE TITLE
Broken with emacs-24.5 due to pcase-dolist.

### ISSUE THREAD

**Issue by thierryvolpiatto** [magit/with-editor#13]
Hi, 
`pcase-dolist` is not available in emacs-24.5.

Thanks.

**Comment by tarsius** [comment]
Ah crap, I have started using it *again*... will fix today.

**Comment by npostavs** [comment]
Maybe enabling CI here could help us too?

**Comment by tarsius** [comment]
> Maybe enabling CI here could help us too?

Sure I have just done that on the `travis` branch.

But that would not help us catch compile warnings. Do you know how to turn those into errors? (I would like if you would still see all warning before compiling is aborted and Emacs exits.)

But even then we would not have caught this. For some reason this does not even give a warning. https://travis-ci.org/magit/with-editor/jobs/280556868

**Comment by tarsius** [comment]
> For some reason

Ah! This is not correct:

> `pcase-dolist` is not available in emacs-24.5.

It's only not *autoloaded*.

Which means that we should *not* only require `pcase` at compile time. (https://github.com/magit/with-editor/commit/1b7f6ef1a5bf5f574e6597adda1a26c3549f2a13#commitcomment-24599013)

**Comment by npostavs** [comment]
> But that would not help us catch compile warnings. Do you know how to turn those into errors?

Yes, I have done this for el-get's test scripts, I will put something up tonight.

> It's only not autoloaded.
> Which means that we should not only require pcase at compile time.

Sorry, I'm getting a bit confused with the not only/only not, could you elaborate please?

**Comment by tarsius** [comment]
We should require it at load-time too.

**Comment by npostavs** [comment]
Hmm, I don't see why; it's a macro so it should only be needed while compiling, no?

**Comment by tarsius** [comment]
Ah you are right.

**Comment by npostavs** [comment]
> > But that would not help us catch compile warnings. Do you know how to turn those into errors?
> 
> Yes, I have done this for el-get's test scripts, I will put something up tonight.

In fact, it was even more trivial than I remembered. For el-get I had made something fancier to disable some warnings on different versions, here we just need to set `byte-compile-error-on-warning`. See #39.
