### ISSUE TITLE
May be a problem in listing Issue

### ISSUE THREAD

**Issue by vanicat** [magit/with-editor#18]
Hello,

I'm not sure if this is really a problem, but when I go to the [https://github.com/magit/with-editor/releases](https://github.com/magit/with-editor/releases) It show the last release has been 2.5.7 when there is a v2.5.9 tags. Does this mean something about the importance, stability or something about the 2.5.9 release, or is this a problem with the way github treat those tags ?

Thanks.

**Comment by tarsius** [comment]
No, I just forgot to "create" those releases.

**Comment by vanicat** [comment]
Okay. Thanks for the explanation.

**Comment by tarsius** [comment]
Thanks for the reminder ;-)
