### ISSUE TITLE
not working on windows10 prerelease, GUI

### ISSUE THREAD

**Issue by Perlmint** [magit/with-editor#21]
OS: Windows 10 Home Insider Preview 15007
Emacs dist: https://sourceforge.net/projects/emacsbinw64/

I installed magit. when emacs try to load magit - load with-editor also, emacs just shows message box few times and finally failed to find suitable emacsclient.
because `emacsclient --version` does not print version to stdout, but shows the message box. so `with-editor-emacsclient-version` not works, it just shows message box and failed to get version string.

**Comment by tarsius** [comment]
> because `emacsclient --version` does not print version to stdout, but shows the message box.

That's very strange and I cannot see anything I could do about it. It shouldn't do that and so it would be best to ask the `emacsbinw64` maintainers about it.

As a workaround you can set `with-editor-emacsclient-executable` to `nil`. Read `with-editor-sleeping-editor`'s doc-string for more information.

**Comment by Perlmint** [comment]
Thanks for your comment, your suggestion works nicely!

**Comment by chwarr** [comment]
On Windows 10 Version 1607 (Build 15004.1000), I tried running `emacsclient.exe --version` on a Emacs 22.3, 23.4, 24.5, and 25.1, all taken from the [GNU FTP server](http://ftp.gnu.org/gnu/emacs/windows/). All of these emacsclient.exe report the version for me in a dialog box, not to stdout.

However, on Windows 10 Version 1607 (Build 14393.105), `emacsclient --version` for 25.1 writes to stdout. Something looks to have changed in Windows itself. I've reported this issue via the [Feedback Hub](https://aka.ms/q5ib73).

**Comment by fpopineau** [comment]
The upcoming "Creators Update" release of Windows 10 will confirm this behaviour change (probably, due on April 5th).

This is not the place to discuss this, but I think it is a mistake that emacsclient.exe (which is supposed to be a console application) be able to report either on stdout or using modal dialog boxes depending on some guess.
There are 2 different programs : emacsclient.exe and emacsclientw.exe . Each of them should report with its own modality.

**Comment by Dessix** [comment]
I've been able to successfully run Magit as expected for about 2 weeks now- seems fixed?
