### ISSUE TITLE
systemctl edit command fails

### ISSUE THREAD

**Issue by jabranham** [magit/with-editor#31]
Any kind of call to systemctl in an attempt to edit units fails. Example:

```
systemctl --user edit emacs
```

results in 

```
"WITH-EDITOR:: -c: line 0: unexpected EOF while looking for matching `''
"WITH-EDITOR:: -c: line 1: syntax error: unexpected end of file
editor failed with error code 1.
Editing "~/.config/systemd/user/emacs.service.d/override.conf" canceled: temporary file is empty.
```

Here's how I load with-editor

```
(use-package with-editor
  :ensure t
  :init
  (progn
    (add-hook 'shell-mode-hook  'with-editor-export-editor)
    (add-hook 'eshell-mode-hook 'with-editor-export-editor))
  :config
  (shell-command-with-editor-mode))
```

**Comment by tarsius** [comment]
The problem seems to be with `systemctl`:

```
$ systemctl --force --user edit foobar
"WITH-EDITOR:: 1: "WITH-EDITOR:: Syntax error: Unterminated quoted string
editor failed with error code 2.
Editing "/home/jonas/.config/systemd/user/foobar.service" canceled: temporary file is empty.
$ git commit --allow-empty
WITH-EDITOR: 13488 OPEN /home/jonas/.git/modules/emacs.d/modules/with-editor/COMMIT_EDITMSG
[gelpa 2d6f50c] test
$
```

Could you please try to find some documentation about what assumptions it makes about the value of `$EDITOR`? It looks like it some how chops of part of it. The value set by `with-editor` looks like `sh -c '...'`.

**Comment by jabranham** [comment]
In `man systemctl`, it just says:

```
ENVIRONMENT
       $SYSTEMD_EDITOR
           Editor to use when editing units; overrides $EDITOR and $VISUAL. If neither $SYSTEMD_EDITOR nor $EDITOR nor $VISUAL are present or if it is set
           to an empty string or if their execution failed, systemctl will try to execute well known editors in this order: editor(1), nano(1), vim(1),
           vi(1).
```

**Comment by npostavs** [comment]
Similar problem in Emacs Bug#[9051](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=9051)/[25082](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=25082):

> The documentation in environ(7) just says:
> 
>        EDITOR/VISUAL
>               The user's preferred utility to edit text files.
> 
> However, I can't find a program that interprets it as a literal filename.
> 
> For example, Debian's sensible-editor editor-wrapper script does exactly
> what I just did. If I set
> 
>     export EDITOR='"spacey editor"'
> 
> it complains it can't find a program called: "spacey
> 
> If I do
> 
>      export EDITOR="emacsclient -c"
> 
> it works nicely. So it doesn't parse quotes specially. However, that's not
> cross-platform.

**Comment by tarsius** [comment]
> Similar problem in Emacs

But that is the only relation to the issue at hand. The problem in this case isn't that Emacs doesn't attempt to handle `ALTERNATE_EDITOR` as one would expect but that `systemd`, while trying to do so, actually fails to handle `EDITOR`/`SYSTEMD_EDITOR` as one would expect.

`systemd` can handle something like `EDITOR="emacsclient -c"`. However if the value contains a quote or double quote, then it fails:

```
% SYSTEMD_EDITOR="sh -c \"echo huhu\"" systemctl --force --user edit foobar      
huhu": 1: huhu": Syntax error: Unterminated quoted string
editor failed with error code 2.
Editing "/home/jonas/.config/systemd/user/foobar.service" canceled: temporary file is empty.

% SYSTEMD_EDITOR="sh -c 'echo huhu'" systemctl --force --user edit foobar  
huhu': 1: huhu': Syntax error: Unterminated quoted string
editor failed with error code 2.
Editing "/home/jonas/.config/systemd/user/foobar.service" canceled: temporary file is empty.
```

There is nothing we can do here to work around this issue, so I am closing this.
