### ISSUE TITLE
error: Bad bounding indices: 0, 3

### ISSUE THREAD

**Issue by scottross8** [magit/with-editor#33]
This error is coming from the cl-subseq call in the with-editor-locate-emacsclient-1 function.   I'm running emacs "25.2" so the split-string only gets a 2 element list.

I've found 2 ways to fix it.   One is to concat and extra ".0" to emacs-version.  Either globally or in the let* of with-editor-locate-emacsclient-1.   The other is to replace the hard 3 in with-editor-locate-emacsclient with `(length (split-string emacs-version "\\."))`

**Comment by tarsius** [comment]
> I'm running emacs "25.2" so the split-string only gets a 2 element list.

I have never seen Emacs identify itself as just `N.M`, and have only ever seen `N.M.1`. Out of curiosity, how did you install Emacs to end up with an installation that strips the constant noise at the end?

**Comment by npostavs** [comment]
I believe Emacs 26 will drop the last number, but I'm also a bit confused how you managed to get 25.2 to do so.

https://debbugs.gnu.org/cgi/bugreport.cgi?bug=25590

**Comment by scottross8** [comment]
This was installed through the package manager but it is for the ARM processors on Linux (termux).   I doubt that Fredrik spent extra time messing with Emacs' version string, but whoever ported to ARM may have.

    GNU Emacs 25.2 (aarch64-unknown-linux-android)
     of 2017-08-16
    Copyright (C) 2017 Free Software Foundation, Inc.

**Comment by jasonm23** [comment]
Same issue for me, thanks for the workardound.

**Comment by jdtsmith** [comment]
I encountered this with Emacs 26.1.  I had to update the `with-editor` package, which solved it.  `magit` may need a dependency on the `with-editor` version to force this update.
