### ISSUE TITLE
Can't find emacsclient if default-directory doesn't exist

### ISSUE THREAD

**Issue by phst** [magit/with-editor#34]
It seems that `with-editor-locate-emacsclient` fails if `default-directory` doesn't exist. For example, with a current master build of Emacs and `with-editor`:

```none
$ /correct/path/to/emacs/src/emacs -Q -batch -l ./with-editor.el -eval '(print (with-editor-locate-emacsclient))'
"/correct/path/to/emacs/lib-src/emacsclient"
```

But:

```none
$ /correct/path/to/emacs/src/emacs -Q -batch -l ./with-editor.el -eval '(let ((default-directory "/does/not/exist/")) (print (with-editor-locate-emacsclient)))'
Warning (with-editor): Cannot determine a suitable Emacsclient

Determining an Emacsclient executable suitable for the
current Emacs instance failed.  For more information
please see https://github.com/magit/magit/wiki/Emacsclient.

nil
```

**Comment by phst** [comment]
I think the issue is simply that the `process-lines` in `with-editor-emacsclient-version` doesn't work if the current directory doesn't exist. Probably that should just be bound to a directory know to exist, e.g. `/` or `execution-directory`.

**Comment by phst** [comment]
Confirmed that it works if I surround the body of `with-editor-emacsclient-version` with a `(let ((default-directory "/")) ...`.

**Comment by tarsius** [comment]
Thanks!

I think `/` isn't valid on Windows and I am not sure that we can be certain that `exec-directory` (not `execution-directory`) exits. So I went with `(file-name-directory exec)`.

**Comment by npostavs** [comment]
> I think `/` isn't valid on Windows

It does seem to work, although it gets converted to `c:/` (by Emacs?).

**Comment by phst** [comment]
`\` is the root directory of the current drive. That should work if the current drive is valid. However, I guess `default-directory` could also include an invalid drive, such as `Y:\Does\Not\Exist`. So I guess `(file-name-directory exec)` should be safest (if that directory doesn't exist, we can't execute the process anyway).
