### ISSUE TITLE
Recent commit breaks emacsclient

### ISSUE THREAD

**Issue by franburstall** [magit/with-editor#38]
Commit ae2324336b1483fbfdbc50e414c625144f62c962 breaks emacsclient for me: it fails with 

*ERROR*: Invalid function: (\` ((\, file) \, _))

I suspect the pcase-dolist in that commit is malformed.

This is emacs 24.4 under Linux Mint Debian Edition.  Output of with-editor-debug:

with-editor: /u/c/feb/.emacs.d/elpa/with-editor-20170924.1057/with-editor.el
emacs: /usr/bin/emacs (24.4.1)
system:
  system-type: gnu/linux
  system-configuration: x86_64-pc-linux-gnu
  system-configuration-options: --build x86_64-linux-gnu --prefix=/usr --sharedstatedir=/var/lib --libexecdir=/usr/lib --localstatedir=/var/lib --infodir=/usr/share/info --mandir=/usr/share/man --with-pop=yes --enable-locallisppath=/etc/emacs24:/etc/emacs:/usr/local/share/emacs/24.4/site-lisp:/usr/local/share/emacs/site-lisp:/usr/share/emacs/24.4/site-lisp:/usr/share/emacs/site-lisp --build x86_64-linux-gnu --prefix=/usr --sharedstatedir=/var/lib --libexecdir=/usr/lib --localstatedir=/var/lib --infodir=/usr/share/info --mandir=/usr/share/man --with-pop=yes --enable-locallisppath=/etc/emacs24:/etc/emacs:/usr/local/share/emacs/24.4/site-lisp:/usr/local/share/emacs/site-lisp:/usr/share/emacs/24.4/site-lisp:/usr/share/emacs/site-lisp --with-x=yes --with-x-toolkit=gtk3 --with-toolkit-scroll-bars 'CFLAGS=-g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wall' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-z,relro
server:
  server-running-p: t
  server-process: #<process server>
  server-use-tcp: nil
  server-name: server
  server-socket-dir: /tmp/emacs1134
    server
    server4575
  server-auth-dir: ~/.emacs.d/server/
    WARNING: not an accessible directory
with-editor-emacsclient-executable:
 value:   /usr/bin/emacsclient.emacs24 (24.4)
 default: /usr/bin/emacsclient.emacs24 (24.4)
 funcall: /usr/bin/emacsclient.emacs24 (24.4)
path:
  $PATH: ".:/u/c/feb/scripts:/u/c/feb/bin:/u/c/feb/bin.x86_64:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games"
  exec-path: (. /u/c/feb/scripts /u/c/feb/bin /u/c/feb/bin.x86_64 /usr/local/bin /usr/bin /bin /usr/local/games /usr/games /usr/lib/emacs/24.4/x86_64-linux-gnu)
  with-editor-emacsclient-path:
    . (t)
    /u/c/feb/scripts (t)
    /u/c/feb/bin (t)
    /u/c/feb/bin.x86_64 (nil)
    /usr/local/bin (t)
    /usr/bin (t)
      /usr/bin/emacsclient (24.4)
      /usr/bin/emacsclient.emacs24 (24.4)
    /bin (t)
    /usr/local/games (t)
    /usr/games (t)
    /usr/lib/emacs/24.4/x86_64-linux-gnu (t)

**Comment by tarsius** [comment]
I suspect the problem is that I did not explicitly require `pcase`. That is autoloaded in `25.3`, but maybe not in earlier releases. Could you try again after explicitly loading `pcase` please?

**Comment by franburstall** [comment]
Yup: `(require 'pcase) ` solves the problem.

Many thanks for yr very quick response.

**Comment by tarsius** [comment]
Okay, added that to the library too.

You are welcome!
