### ISSUE TITLE
Using C-x C-c in emacsclient doesn't behave as expected

### ISSUE THREAD

**Issue by vy-let** [magit/with-editor#42]
In recent versions (within the last few months, I'm not sure), when I open a session with `emacsclient -t` and then attempt to finish with `C-x C-c`, I get the warning "Don’t kill this buffer. Instead cancel using C-c C-k." Of course, using `C-c C-c` at this point does what I want to do, but it seems an unnecessary complication, considering how

1.  `C-x C-c` has so much muscle-memory behind it;
2.  my impression has always been that `C-x C-c` is supposed to "do the right thing" inside an emacsclient session; and
3.  it's worked in the past under `with-editor`.

Of course, I understand there's likely some fundamental misunderstanding on my part.

I originally installed this package as a dependency of `git-commit`, which has been super useful for me.

Thanks!

**Comment by tarsius** [comment]
> my impression has always been that `C-x C-c` is supposed to "do the right thing" inside an emacsclient session; and

Which is why `with-editor` doesn't use it. For actions like writing a commit message at least it makes sense to have two options and we cannot guess which is the right one: 1. tell the process that you are done and it can use the file's content now, and 2. tell it that you changed your mind and it should not use the file's content.

> it's worked in the past under `with-editor`.

It always was the intention for this to happen but didn't until a recent bugfix (#23). But that is causing some issues (#40, this), so I might have to rethink that change.

**Comment by vy-let** [comment]
I think the reasoning for requiring a commit or discard action makes sense, from the perspective of an action launched from magit. The core of the issue, as far as I can tell, is how this now leaks over into *all* emacsclient sessions, even those launched manually and for file buffers of every major mode.

**Comment by tarsius** [comment]
> In recent versions (within the last few months, I'm not sure), when I open a session with `emacsclient -t` and then attempt to finish with `C-x C-c`, I get the warning "Don’t kill this buffer. Instead cancel using C-c C-k."

I cannot reproduce this. For me `C-x C-c` always invokes `save-buffers-kill-terminal` regardless of whether `with-editor` has been loaded or not.

> my impression has always been that `C-x C-c` is supposed to "do the right thing" inside an emacsclient session

My impression was (it says so in the echo area) that you are supposed to use `C-x #`, which is bound to `server-edit`. Hmm, that's what you use to *confirm*. I never use `emacsclient -t`, so I can only guess that `C-x C-c` is indeed what you are supposed to do to cancel.

> The core of the issue, as far as I can tell, is how this now leaks over into *all* emacsclient sessions, even those launched manually and for file buffers of every major mode.

As I said, I cannot reproduce that.

**Comment by tarsius** [comment]
I have just reverted a change that likely is related to the behavior you saw. So even though I was not able to reproduce this, it should now be "fixed".
