### ISSUE TITLE
Is it a good idea to change `server-name' 's value?

### ISSUE THREAD

**Issue by xor3** [magit/with-editor#43]
https://github.com/magit/with-editor/blob/ee39f232f2daf997498a4030d104c35ae397f457/with-editor.el#L428-L433

Is it a good idea to change `server-name` 's value? 
Someone maybe use `server-name` outside emacs,  such as using emacsclient with server or socket file name which is same as default `server-name` value.

**Comment by tarsius** [comment]
The `server-name` is only changed for the current Emacs instance if another Emacs instance is already using the default value. So if you now use `emacsclient` to connect to the default socket, then that will result in a connection to the first Emacs instance.
