### ISSUE TITLE
should not with-editor start a server with a specific name?

### ISSUE THREAD

**Issue by zil** [magit/with-editor#44]
https://github.com/magit/with-editor/blob/ee39f232f2daf997498a4030d104c35ae397f457/with-editor.el#L429

https://github.com/magit/with-editor/blob/ee39f232f2daf997498a4030d104c35ae397f457/with-editor.el#L433

A bit about how I use emacs:
 > one emacs for org-mode with magit to sync files
 > another emacs daemon used by emacsclient for other edit task.

What frustrate me is once I used magit in the first emacs, the other emacs daemon will not start properly.

Would it not be better if with-editor always use a unique server-name no matter what the current server-name is.

**Comment by tarsius** [comment]
> Would it not be better if with-editor always use a unique server-name no matter what the current server-name is.

I don't think so.

* An Emacs instance can run only one server.
* Most users use only one Emacs instance.
* Using the standard name avoids breaking things that assume that that is used.

I don't know how exactly using the standard name breaks your setup, but you can easily configure `with-editor` to use another name simply by setting `server-name` before `with-editor` is used for the first time.

**Comment by zil** [comment]
Yeah,my starting two Emacs instances with two servers is unusual.
I had fixed the  issue with the solution you mentioned.
Thanks.
