### ISSUE TITLE
with-editor-export-editor sets the environment variable, but editing something opens an empty buffer

### ISSUE THREAD

**Issue by parhamdoustdar** [magit/with-editor#52]
First off, my environment:

- GNU Emacs 26.1 (build 1, x86_64-apple-darwin14.5.0, NS appkit-1348.17 Version 10.10.5 (Build 14F2511)) of 2018-05-28
- MaGit version 20180612.1617
- with-editor version 20180414.757

Here is what happens:

- I run a command that requests an editor
- A new buffer opens that has the address to some temporary file
- Killing with `C-c C-k` or saving with `C-c C-c` returns me to the `*shell*` buffer, where the sleep command is still stuck.

At this point, I have to use `C-c C-c` in the shell buffer to get my prompt back.

**Comment by npostavs** [comment]
> However, when I eval (process-get (get-process "shell") 'default-dir) it returns nil. In fact, the whole process plist is nil.
> 
> When I read the code a bit more, no where in with-editor-export-editor is this value being set.

It gets set in `start-file-process--with-editor-process-filter`, which is applied as advice to `start-file-process`. Is it not getting run in your case?

> MaGit version 20180612.1617

You mention magit, but then it sounds like you aren't actually using magit here?

> Killing with C-c C-k or saving with C-c C-c returns me to the `*shell*` buffer, where the sleep command is still stuck.

Is this purely from a `*shell*` buffer? Can you explain the exact steps you are following, starting from starting Emacs?

**Comment by parhamdoustdar** [comment]
@npostavs Sorry for the confusion. I'll try to clear things up in this comment.

> It gets set in start-file-process--with-editor-process-filter, which is applied as advice to
start-file-process. Is it not getting run in your case?

I have no idea who is supposed to call this, but since you know the workflow better than I do, when I explain how I'm running `with-editor` below, you can tell me how i can verify this.

> You mention magit, but then it sounds like you aren't actually using magit here?

Yes, sorry for the confusion. I thought magit might have a conflict or cause with-editor to misbehave in some way. One of the things I did in the period when with-editor was working for me and now that it isn't, was to install magit. So I thought maybe it has something to do with it not working. That's why I put the version there.

> Is this purely from a *shell* buffer? Can you explain the exact steps you are following, starting from starting Emacs?

Yes, it is from a `*shell*` buffer.

1. I open the shell, and SSH into a remote machine.
2. I run `M-x with-editor-export-editor RET RET`
3. I then run `crontab -e`.

At this point, the buffer opens, pointing to my local file, which doesn't exist.

As I was writing this, I tried this also by opening a remote shell using tramp, instead of SSHing to it from a shell. Running `crontab -e` through the shell buffer I opened after running tramp works as expected, even though there is still no `default-dir` on the `shell` process plist.

Let me know if this is meant to be used from a shell opened after using tramp, or if I'm doing something else wrong, or if I need to provide more info.

**Comment by npostavs** [comment]
> As I was writing this, I tried this also by opening a remote shell using tramp, instead of SSHing to it from a shell. Running crontab -e through the shell buffer I opened after running tramp works as expected, even though there is still no default-dir on the shell process plist.

The `default-dir` on process plist thing is only for processes started by `start-file-process`, not `*shell*` buffer processes.
 
> Let me know if this is meant to be used from a shell opened after using tramp, or if I'm doing something else wrong, or if I need to provide more info.

Yes, I think that's the only way it can work. Otherwise, Emacs directory tracking currently isn't good enough to figure out that you are in a remote directory at all. So this is actually a dup of magit/magit#1638, there is more info about it there, including some possible approaches for making it work better.
