### ISSUE TITLE
Help MacOS + Magit Users solve their "unsuitable" problems)

### ISSUE THREAD

**Issue by cicerojones** [magit/with-editor#53]
Hi, this may be more of a note about documentation than a bug, but, after dealing with the *Warning* message about a suitable EmacsClient (as mentioned in #26), I think it might be nice to be more explicit about how to do the following (for people who are left scratching their heads [at this comment from the documentation](https://magit.vc/manual/with-editor/Configuring-With_002dEditor.html#Configuring-With_002dEditor)):

>...When it fails to do so, then the most likely reason is that someone found yet another way to package Emacs (most likely on macOS) without putting the executable on $PATH, and we have to add another kludge to find it anyway.

I cobbled together a solution by running a version of this command that was suitable to my system and $PATH:

`    ln -s /Applications/Emacs.app/Contents/MacOS/bin/emacsclient /usr/local/bin
`

as described at https://emacsformacosx.com/tips. And then of course adding to my `~/.bashrc`):

`alias emacsclient='/usr/local/bin'` (as modified from a helpful note on the much-maligned wiki https://www.emacswiki.org/emacs/EmacsForMacOS#toc19)

As suggested in the documentation above, there are many ways to do this (and thus many ways to do this wrong!), but, if nothing else, hopefully this report might help point some other poor Mac user in the right direction.

Regardless, thanks again for the Magit-ical work!

**Comment by tarsius** [comment]
> I think it might be nice to be more explicit about how to do the following

Well it worked as intended. The purpose was to get you to contact us . :wink: 

Am I correct in assuming that you first did:

```
ln -s /Applications/Emacs.app/Contents/MacOS/emacs /usr/local/bin
```

and `with-editor` broke until you also did (as mentioned)

```
ln -s /Applications/Emacs.app/Contents/MacOS/bin/emacsclient /usr/local/bin
```

?

Note that there is a `bin/` before `emacs`, but not before `emacsclient`. Please confirm that this really is the case for you too. We already deal with this packaging mistake, which unfortunately is very common among Emacs packages for macOS.

But we don't do so after following a symlink to the `emacs` executable yet. I tried implementing that in the `macos-truedir` branch. Could you please give that a try *after* removing the `emacsclient` symlink (but keeping the `emacs` symlink).

**Comment by cicerojones** [comment]
You expect me to understand what I have done??? But I'm using Emacs!! 🎉  

Honestly, I don't think I ever really got as far as doing something that would require`with-editor` at all; I just received that warning message ("Cannot determine a suitable Emacsclient") in a *Warnings* buffer upon starting Emacs, but it appears this is because I was actually starting the binary from the command line with `--debug-init` (as opposed to opening Emacs via the "Emacs.app" icon, as is customary with applications on MacOS. **NB. The error message does *NOT* appear when I open Emacs that way**, though using the command line and dropping the `--debug-init` still gives the warning)

So, I didn't actually use what you assumed was my first attempt at making a symbolic link, just the second one, though the exact path for the emacsclient, using one of the "Nightlies" versions of Emacs packaged at https://emacsformacosx.com/builds, does appear to have a `bin` prefix of a sort:
 
`/Applications/Emacs.app/Contents/MacOS/bin-x86_64-10_9/emacsclient`

And so that is what I symlinked in (i.e. basically the second code block in your reply above).

Honestly, I wasn't actually having any problems with magit, but I'm also not really using the `emacsclient`. It's very likely there's something not quite right with how I've configured things on my side. My workflow is not particularly affected by using Emacs.app "from the dock" vs. `/Applications/Emacs.app/Contents/MacOS/Emacs-x86_64-10_9` "from the CLI."

Does any of that help? Please let me know if there's something you'd like me to do. I didn't fully understand what "that" meant in 
> Could you please give that a try
