### ISSUE TITLE
WITH-EDITOR... line doesn't work from a program that changes directory

### ISSUE THREAD

**Issue by raeburn** [magit/with-editor#55]
I'm using a remote shell to explore a git checkout tree, run diffs, and do commits. (Yes, I know, should learn magit one of these days. :-) I used with-editor-export-editor to set $EDITOR in the shell process.

If I'm in a subdirectory of the git tree (not the top level), then "git commit" appears to invoke the editor from the top of the tree, with a path like ".git/COMMIT_EDITMSG"; running "lsof -p" on the "sleep" process run in the with-editor shell command confirms that its working directory is the top of the tree, not the directory where I invoked git from my shell, and therefore not the directory specified in default-directory (which is set correctly for my interactive shell's directory). So with-editor tries to edit a file that doesn't exist ($git_top/some/subdir/.git/COMMIT_EDITMSG), tells me how to create the non-existent .git directory, etc.

I'm experimenting with a change to the shell command to use something like:
case "$0" in
  /*) echo ... $0 ... ;;
  *) echo ... $(pwd -L)/$0 ... ;;
esac; ...

and at least at first it seems to work.

**Comment by tarsius** [comment]
My attempt in #56 does more of the work in elisp. Also I use `pwd` instead of `pwd -L`, which [posix says](http://pubs.opengroup.org/onlinepubs/009696899/utilities/pwd.html) shall be equivalent. Please try it out.

**Comment by tarsius** [comment]
What Git version are you using? 2.19.0 does not have this issue because it passes the absolute file-name to the `$EDITOR`.

Since this has been addressed for Git, I think there is nothing left to be done here. If a program changes the directory *and* does not use an absolute file-name, then I would consider that a bug. If we find other, up-to-date, programs that do this, then we can still reconsider, I will keep the branch with the proposed workaround alive for a while.

**Comment by tarsius** [comment]
Changed my mind for the reason given in the commit message. Also I was able to do this in a backward compatible fashion.

**Comment by raeburn** [comment]
I believe I'm using Fedora 28 and RHEL 7 supplied versions on my test systems -- versions range from 1.8.3 to 2.17.1. I'd prefer not to have to install an updated git manually on all the remote machines I use, especially since the machines themselves frequently get reinstalled in our dev/test processes.

The change in #56 looks good to me, and in a quick test it seems to work fine. (Minor nits: The doc string for the sleeping editor echos lowercase "in" in the alternate implementation where the default setting and the regexp use uppercase "IN". And it might be good to call out the fact that the string printed out includes a control character, in case the user tries typing the alternate version into a shell instead of copying the block via emacs.)

**Comment by raeburn** [comment]
BTW, thanks for fixing it! :-)

**Comment by tarsius** [comment]
You're welcome.

I have updated the documentation.
