### ISSUE TITLE
with-editor unavailable on MELPA, failing installaions

### ISSUE THREAD

**Issue by ansxor** [magit/with-editor#58]
After trying to install Magit on a new Emacs configuration, it is unable to install from Melpa as it is the latest version appears to be unavailable.

How I produced this:
`(use-package magit
  :ensure t
  :bind
  ("C-x g" . magit-status)
  ("C-x M-g" . magit-dispatch-popup))`
> (use-package): Failed to install magit: https://melpa.org/packages/with-editor-20181031.1658.tar: Not found

`(package-install with-editor)`
> https://melpa.org/packages/with-editor-20181031.1658.tar: Not found

**Comment by tarsius** [comment]
A more recent version of `with-editor` is available from Melpa: http://www.melpa.org/#/with-editor.

Doing `M-x package-refresh-contents` should fix this.

**Comment by ansxor** [comment]
This solved the issue.
