### ISSUE TITLE
Revert or provide config handle for old exit behavior

### ISSUE THREAD

**Issue by frozencemetery** [magit/with-editor#66]
Hi, I understand that the change to exiting is intentional.  However, I'd like to ask that either the change be reverted or a handle be provided for the old behavior.

The problem is that on machines *without* magit/with-editor installed, saving a nonempty commit_message buffer and exiting causes the commit to go through properly.  As I understand it, this is because git is checking the exit status of the $EDITOR process to determine whether to commit, and an unclean exit is treated as "abort commit".

Having a different contract here makes learning the muscle memory difficult, but there is also the problem that if I accidentally save and C-x C-c, with with-editor, the contents of the commit message are lost, which I consider unacceptable.

I understand you prefer the new behavior, but could you at least provide a handle to restore the old?

**Comment by tarsius** [comment]
Are you committing from Magit or manually using `git commit` in a terminal?

**Comment by tarsius** [comment]
If I initiate the commit from the command line, then the behavior depends on whether `emacs` or `emacsclient` is used. If its the former, then then the commit is created. If it is the latter, then I was asked `This Emacs session has clients; exit anyway?`, at which point one should abort.

**Comment by tarsius** [comment]
When you try to `C-x C-c`, then Emacs now refuses to do it. You can then `C-c C-k` instead, and that won't deleted `.git/COMMIT_EDITMSG`.

Note however while `with-editor` no longer causes the file to be deleted, the next time you invoke `git commit` THAT will delete it. In other words there now is a backup of the message saved in the file after you have aborted, but you have to move that backup to a safe place to prevent Git itself from later discarding it.
