### ISSUE TITLE
git-commit-post-finish-hook possible bug

### ISSUE THREAD

**Issue by dickmao** [magit/with-editor#68]
One thing I noticed when developing magit-patch-changelog was I couldn't make git-commit-post-finish-hook work.  I traced it down to [this line](https://github.com/magit/with-editor/blob/814777ce8ad42ad115eebc38743c55b99af5d2e7/with-editor.el#L346) always being false after `with-editor-return` kills the COMMIT_MSG buffer.

MWE:
```
emacs -Q --batch -L . -l with-editor --eval "(package-initialize)" -l magit --eval "(with-temp-buffer \
    (defun git-commit-run-post-finish-hook () \
      (setq flag 1) \
      (run-hooks 'git-commit-post-finish-hook)) \
    (setq-local git-commit-post-finish-hook '((lambda () (setq flag 2)))) \
    (add-hook 'with-editor-post-finish-hook 'git-commit-run-post-finish-hook)
    (with-editor-finish nil) \
    (cl-assert flag) \
    (cl-assert (featurep 'git-commit)) \
    (cl-assert (= flag 2)))"
```

Given git-commit-run-post-finish-hook's already [dubious standing](https://github.com/magit/magit/blob/bbb755267a5373774e6b0e61fbc486ea485fad93/lisp/git-commit.el#L568), I might consider removing the variable altogether.

**Comment by tarsius** [comment]
Have you tried adding `(require 'git-commit)` to your library?

**Comment by dickmao** [comment]
I updated the MWE to load magit (and consequently git-commit).

**Comment by tarsius** [comment]
And that fixed it? What is MWE? Can I see the update somewhere?

**Comment by tarsius** [comment]
It indeed looks weird how that hook is called and the commit does shed any light on it.

**Comment by dickmao** [comment]
MWE = Minimum Working Example.  I find people reporting issues don't spend
enough time to make these.

I expect none of the assertions to fail (but the last one does).

Unfortunately, the logic going from `with-editor-post-finish-hook` to
`git-commit-post-finish-hook` is a tad convoluted, but I tried my best
affine transform of it in the MWE.

I was happy to let things lie, but a [recent reddit
post](https://www.reddit.com/r/emacs/comments/ee5o6g/commiting_orgmode_files_to_github_pages/)
reminded me that buffer-localizing git-commit-post-finish-hook didn't work for me.
If the intention is for git-commit-post-finish-hook to only ever be globally
bound, then there is no issue (replacing setq-local with setq above works).

**Comment by tarsius** [comment]
> I find people reporting issues don't spend enough time to make these.

I applaud you for doing it but because I don't use package.el, I first had to port it to the `emacs-Q` make target:

```diff
diff --git a/Makefile b/Makefile
index edb0af85c..bc50185cf 100644
--- a/Makefile
+++ b/Makefile
@@ -120,6 +120,13 @@ emacs-Q: clean-lisp
        @$(EMACSBIN) -Q $(LOAD_PATH) --debug-init --eval "(progn\
        (setq debug-on-error t)\
        (require 'magit)\
+       (defun git-commit-run-post-finish-hook () \
+         (run-hooks 'git-commit-post-finish-hook)) \
+       (add-hook 'git-commit-post-finish-hook (lambda () (message \"GLOBAL\"))) \
+       (with-temp-buffer \
+         (add-hook 'git-commit-post-finish-hook (lambda () (message \"LOCAL\")) nil t) \
+         (add-hook 'with-editor-post-finish-hook 'git-commit-run-post-finish-hook) \
+         (with-editor-finish nil)) \
        (global-set-key \"\\C-xg\" 'magit-status))"
 
 ## Clean #############################################################
```

Anyway, I think the condition should simply be replaced with `post-command-hook`. Please give that a try.

**Comment by dickmao** [comment]
So your advice is "use post-command hook instead of
git-commit-post-finish-hook"?  That can't be right, can it?  Not only is
`post-command-hook` widely recognized as dangerous territory since it
follows every user input, but using it skirts this issue entirely.

As I say, I don't think it's a big deal and am happy to close it.  I am also
skeptical about the logic that if git cannot commit within a second, then
git-commit-post-finish-hook never runs.  I think we can both agree
conditioning behavior on how long a system call takes is fraught.

Please let me know if you want to take action, and if not, I shall close (or
you can do it).  Thanks.

**Comment by tarsius** [comment]
No I am saying `with-editor.el` has a bug which can be fixed like so:

```diff
diff --git a/with-editor.el b/with-editor.el
index a35b6f8..19198da 100644
--- a/with-editor.el
+++ b/with-editor.el
@@ -343,7 +343,7 @@ (defun with-editor-finish (force)
       (with-temp-buffer
         (setq default-directory dir)
         (setq-local with-editor-post-finish-hook post-finish-hook)
-        (when (bound-and-true-p git-commit-post-finish-hook)
+        (when post-commit-hook
           (setq-local git-commit-post-finish-hook post-commit-hook))
         (run-hooks 'with-editor-post-finish-hook)))))

```

And I just want you to quickly try that before I push it to `master`.

**Comment by dickmao** [comment]
Yes, that works.  Thanks.
