### ISSUE TITLE
Something goes wrong when connecting to socket created by systemd

### ISSUE THREAD

**Issue by vp1981** [magit/with-editor#7]
Please consider to add an user option (variable) to set path to socket file.

Long story:

Beginning with commit ["Add external socket launching support"](http://git.savannah.gnu.org/cgit/emacs.git/commit/?id=e390b7b54651d3c5a4c36168e84e96e197631f41) there is possibility to start Emacs daemon using external socket. There is special variable to reflect this: `:use-external-socket` but of course there is no way to determine the name of a socket and its path within Emacs (the example how to use socket activation of Emacs daemon is in documentation, one may find them in the same commit ). For such cases an user option would help to use `magit` that uses `with-editor` in turm.

**Comment by vp1981** [comment]
I have made a ["dirty" patch](https://gist.github.com/vp1981/4bbf8961f84ab9fb46e24248df2d7515) that allows me to manually set path to socket. I tested it a bit and it works for me.

**Comment by tarsius** [comment]
I don't think adding additional variables is the right approach - other users change the values of the existing variables `server-name` and `server-socket-dir` *after loading `with-editor` and expect `with-editor` to respect those settings.

You can probably just change the values of *these* variables instead.

> but of course there is no way to determine the name of a socket and its path within Emacs

The comment you linked to seems to suggest that this indeed isn't the case (but maybe that has been adressed since?). So you have to manually configure systemd and emacs to use the same value, but for that we don't need additional variables.

**Comment by vp1981** [comment]
Ok, I made some tests.

I created new user on my system, then created a sample git repository. For all tests I used the following `.emacs` file:
```
(add-to-list 'load-path "/usr/share/emacs/site-lisp/dash")
(add-to-list 'load-path "/usr/share/emacs/site-lisp/magit")
(require 'magit)
(global-set-key (kbd "C-x g") 'magit-status)
```

Then I did following tests:
1. run emacs as usual (just run it in terminal), in `*scratch*` buffer I run (in all cases):
```
(format "SERVER NAME: '%s'" server-name)
(format "SERVER SOCKET DIR: '%s'" server-socket-dir)
```
and got
```
SERVER NAME: 'server'
SERVER SOCKET DIR: '/tmp/emacs$UID'
```
(I use here `$UID` instead of real number, because it is unimportant part). magit works fine.
2. Started emacs in daemon mode: `emacs --daemon`, run `emacsclient -c` and got
```
SERVER NAME: 'server'
SERVER SOCKET DIR: '/tmp/emacs$UID'
```
magit works fine.
3. Started emacs in daemon mode with non-default path:
```
emacs --daemon=$XDG_RUNTIME_DIR/emacs
```
and run `emacsclient -s $XDG_RUNTIME_DIR/emacs -c` and got
```
SERVER NAME: '$XDG_RUNTIME_DIR/emacs'
SERVER SOCKET DIR: '/tmp/emacs$UID'
```
magit works fine.
4. Here I used new way to start daemon using socket managed by systemd. I created `.service` and `.socket` files found in Info (info:emacs). For socket I set path `$XDG_RUNTIME_DIR/emacs`. For this case I tested two different variants:
a) without setting variables `server-name` and `server-socket-dir` in `.emacs`
b) and setting these variables in `.emacs`:
```
(setq
  server-name "emacs"
  server-socket-dir (getenv "XDG_RUNTIME_DIR")
)
```
just after `(require 'magit)`.

Results: for both I run `emacsclient -c -s $XDG_RUNTIME_DIR/emacs`
4.a)
```
SERVER NAME: 'server'
SERVER SOCKET DIR: '/tmp/emacs$UID'
```
magit works partially, I can stage changed file but I cannot commit it (I see message `GitError...` with `--socket-dir=/tmp/emacs$UID`).
4.b) Nothing, starting emacsclient kills service.

In all cases variable `XDG_RUNTIME_DIR` (it is set by systemd, I think) points to `/run/user/$UID`.

Still, there can be some errors on my side, may be I incorrectly set these two variables (the output from 3 case looks a bit odd to me), but tests show me that without possibility to set socket name and socket dir I can't get working magit.

**Comment by tarsius** [comment]
Please try again by literally typing the same path into both the systemd and the Emacs configuration files (in the latter case split across the two variables of course), instead of using an environment variable. I suspect that the issue is that Emacs cannot actually see the envvar.

> (the output from 3 case looks a bit odd to me)

If the output really contains `$XDG_RUNTIME_DIR/` (not it's value), then yes, that's wrong.

**Comment by vp1981** [comment]
Hello tarsius,

seems I was unclear: all these `$XXX` variables were used only to hide unimportant parts. For example `/tmp/emacs$UID` was actually `/tmp/emacs1001` and etc.

There were two places where I used variables: when I set `server-socket-dir` variable (in `.emacs` file, I'll try to set the path explicitly) and when I run `emacsclient -c -s $XDG_RUNTIME_DIR`. Would it be more clear if I'll make screenshots?

**Comment by tarsius** [comment]
> seems I was unclear

Yes, I we are trying to figure out if the values of variables are really what you expect them to be, so replacing the values with the variable names in the output does not help.

This is what you should do:
1. Figure out the path of the socket. Check that the file exists.
2. Edit `~/.emacs.d/init.el` to contain (assuming the file name is `/path/to/socket`) `(setq server-socket-dir "/path/to" server-name "socket")`.
3. Restart your computer (not strictly necessary, but let's avoid additional complications).
4. Connect to the Emacs demon.
5. Commit using Magit.

**Comment by vp1981** [comment]
Ok, let's try again.

I tested only **systemd way** to start Emacs daemon. For this I used following `emacs.socket` file:
```
[Socket]
ListenStream=%t/emacs

[Install]
WantedBy=sockets.target
```
following `emacs.service` file:
```
[Unit]
Description=Emacs

[Service]
Type=forking
ExecStart=/usr/bin/emacs --daemon
ExecStop=/usr/bin/emacsclient --eval "(kill-emacs)"
Restart=always

[Install]
WantedBy=default.target
```
and following `.emacs` file:
```
(add-to-list 'load-path "/usr/share/emacs/site-lisp/dash")
(add-to-list 'load-path "/usr/share/emacs/site-lisp/magit")
(require 'magit)
(setq
  server-name "emacs"
  server-socket-dir "/run/user/1001"
)
(global-set-key (kbd "C-x g") 'magit-status)
```

### Tests

#### First run

`1.` Before I started `emacs.socket` there was no `emacs` socket in `/run/user/1001`.

`2.` After I started `emacs.socket`:
```
$ systemctl --user start emacs.socket
$ systemctl --user status emacs.socket
● emacs.socket
   Loaded: loaded (/home/vl-lomov/.config/systemd/user/emacs.socket; disabled; vendor preset: enabled)
   Active: active (listening) since Чт 2016-08-11 09:47:10 IRKT; 19s ago
   Listen: /run/user/1001/emacs (Stream)

авг 11 09:47:10 smoon6-1.vl-lomov.ru systemd[1063]: Listening on emacs.socket.
```
(sorry, I ran these commands in my locale) I found `emacs` socket in `/run/user/1001`:
```
$ ls -lA /run/user/1001
итого 0
srw-rw-rw- 1 vl-lomov users   0 авг 11 08:15 bus
drwx------ 2 vl-lomov users  60 авг 11 08:19 dconf
srw-rw-rw- 1 vl-lomov users   0 авг 11 09:47 emacs
dr-x------ 2 vl-lomov users   0 авг 11 08:15 gvfs
drwx------ 2 vl-lomov users 100 авг 11 08:15 keyring
drwx------ 2 vl-lomov users  80 авг 11 08:15 pulse
drwxr-xr-x 3 vl-lomov users 100 авг 11 08:15 systemd
```

`3.` I checked that there was no emacs process (`ps aux | grep vl-lomov | grep emacs`).

* In terminal (`lxterminal`) I ran
```
$ emacsclient -c -s /run/user/1001/emacs
Waiting for Emacs ...
```
and nothing.

`4.` I ran `systemctl --user status emacs.service` to get
```
● emacs.service - Emacs
   Loaded: loaded (/home/vl-lomov/.config/systemd/user/emacs.service; disabled; vendor preset: enabled)
   Active: failed (Result: start-limit-hit) since Чт 2016-08-11 09:50:59 IRKT; 35s ago
  Process: 2366 ExecStart=/usr/bin/emacs --daemon (code=exited, status=1/FAILURE)

авг 11 09:50:58 smoon6-1.vl-lomov.ru systemd[1063]: Failed to start Emacs.
авг 11 09:50:58 smoon6-1.vl-lomov.ru systemd[1063]: emacs.service: Unit entered failed state.
авг 11 09:50:58 smoon6-1.vl-lomov.ru systemd[1063]: emacs.service: Failed with result 'exit-code'.
авг 11 09:50:59 smoon6-1.vl-lomov.ru systemd[1063]: emacs.service: Service hold-off time over, scheduling restart.
авг 11 09:50:59 smoon6-1.vl-lomov.ru systemd[1063]: Stopped Emacs.
авг 11 09:50:59 smoon6-1.vl-lomov.ru systemd[1063]: emacs.service: Start request repeated too quickly.
авг 11 09:50:59 smoon6-1.vl-lomov.ru systemd[1063]: Failed to start Emacs.
авг 11 09:50:59 smoon6-1.vl-lomov.ru systemd[1063]: emacs.service: Unit entered failed state.
авг 11 09:50:59 smoon6-1.vl-lomov.ru systemd[1063]: emacs.service: Failed with result 'start-limit-hit'.
```
then I ran `systemctl --user status emacs.socket` to get
```
● emacs.socket
   Loaded: loaded (/home/vl-lomov/.config/systemd/user/emacs.socket; disabled; vendor preset: enabled)
   Active: failed (Result: service-start-limit-hit) since Чт 2016-08-11 09:50:59 IRKT; 52s ago
   Listen: /run/user/1001/emacs (Stream)

авг 11 09:47:10 smoon6-1.vl-lomov.ru systemd[1063]: Listening on emacs.socket.
авг 11 09:50:59 smoon6-1.vl-lomov.ru systemd[1063]: emacs.socket: Unit entered failed state.
```

`5.` Again I ran `ps aux | grep vl-lomov | grep emacs` and didn't see any emacs process.

#### Second run

`6.` I rebooted the machine and tried again but this time using the following `.emacs` file:
```
(add-to-list 'load-path "/usr/share/emacs/site-lisp/dash")
(add-to-list 'load-path "/usr/share/emacs/site-lisp/magit")
(require 'magit)
(global-set-key (kbd "C-x g") 'magit-status)
```

`7.` The first three steps were the same but when I ran `emacsclient -c -s /run/user/1001/emacs` in terminal I got almost instantly Emacs frame with `*scratch*` buffer, but when I ran in it
```
(format "SERVER NAME: %s" server-name)
(format "SERVER SOCKET: %s" server-socket-dir)
```
I got in minibuffer
```
SERVER NAME: server
SERVER SOCKET: /tmp/emacs1001
```

`8.` I opened a file in sample git repository, changed it a bit and ran `C-x g`, in opened window I staged it (`s`) but next step, commit changes with `c`, failed with message:
```
  0 git … add -u .
  1 git … commit --
/usr/sbin/emacsclient: can't find socket; have you started the server?
To start the server in Emacs, type "M-x server-start".
/usr/sbin/emacsclient: error executing alternate editor "sh -c 'echo "WITH-EDITOR: $$ OPEN $0"; sleep 604800 & sleep=$!; trap "kill $sleep; exit 0" USR1; trap "kill $sleep; exit 1" USR2; wait $sleep'"
error: There was a problem with the editor '/usr/sbin/emacsclient --socket-name=/tmp/emacs1001/server'.
Пожалуйста, укажите сообщение, при указании опций -m или -F.
```

------------------------------------------------------------------------------------------------

That is my understanding of what is going on: when emacs daemon is started by systemd it has no knowledge about `server-name` and `server-socket-dir` besides the default settings. If one sets them explicitly in `.emacs` then starts daemon by systemd way and then tries to connect to the daemon, the daemon refuses to start. Why? Because systemd already made the socket and (that's my assumption) emacs seeing that there are settings (`server-name` and `server-socket-dir`) for the daemon tries to make socket, again, and fails.

There is a weak point of my assumption but I didn't go deep into procedure of daemon start. The only thing I now that if I set these variables in `.emacs` then start emacs daemon in **usual way** and run `emacsclient` with `-s` pointing to the socket, all works fine.

AFAIR, this (strange) behavior of emacs was the reason why I made patch for `with-editor` and proposed it.

---

P.S. I reread your steps again and think they a bit unclear (as I understand).
> `1`. Figure out the path of the socket. Check that the file exists.

This is simple, I see the path in `emacs.socket`, it is `/run/user/1001/emacs`. But if I didn't enable the `emacs.socket` or didn't start it then there is no such socket. So I enabled the `emacs.socket` and rebooted the machine. After the reboot I see the socket, but this doesn't mean that there is emacs process, because I didn't connect to the socket yet.

> `2`. Edit `~/.emacs.d/init.el` to contain (assuming the file name is `/path/to/socket`) (`setq server-socket-dir "/path/to" server-name "socket"`).

Before the reboot and immediately after it my `.emacs` was
```
(add-to-list 'load-path "/usr/share/emacs/site-lisp/dash")
(add-to-list 'load-path "/usr/share/emacs/site-lisp/magit")
(require 'magit)
(global-set-key (kbd "C-x g") 'magit-status)
```
Then I added settings so now `.emacs` is
```
(add-to-list 'load-path "/usr/share/emacs/site-lisp/dash")
(add-to-list 'load-path "/usr/share/emacs/site-lisp/magit")
(require 'magit)
(setq
  server-name "emacs"
  server-socket-dir "/run/user/1001"
)
(global-set-key (kbd "C-x g") 'magit-status)
```

Again, there is no any emacs process because I didn't connect to the socket.

> `3`. Restart your computer (not strictly necessary, but let's avoid additional complications) and make sure the demon is restarted (check for the socket file again).

Done, there is the socket but
> make sure the demon is restarted

is unclear to me: systemd creates a socket and waits when someone connects to it in order to start appropriate service, in our case the emacs daemon, `emacs.service`.

> `4`. Connect to the Emacs demon.

I did this running in terminal `emacsclient -c -s /run/user/1001/emacs` and saw in terminal
```
Waiting for Emacs ...
```
and nothing, like above.


Hope this will help and sorry for long post.

**Comment by tarsius** [comment]
I've now tried myself and got similar results. I have no experience using systemd and am afraid that means I can help you. Please look for help elsewhere, maybe by asking the author of this feature in Emacs. If you can get it to work, then please post instructions here.

> Because systemd already made the socket and (that's my assumption) emacs seeing that there are settings (server-name and server-socket-dir) for the daemon tries to make socket, again, and fails.

I don't think that is the case because these variables are regular lisp variables and it is my understanding that changing the value of such a variable cannot trigger any action (unless it's value is regularly checked using a timer). Also I know that at least when systemd is not involved changing the values of these variables does not do anything by itself.

**Comment by kryptt** [comment]
For posterities sake: 

```
(setq
  server-name "emacs"
  server-socket-dir (getenv "XDG_RUNTIME_DIR")
)
```

seems to have worked for me

**Comment by tarsius** [comment]
Thanks!

**Comment by Koekelas** [comment]
This is a [known bug](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=24218) and will be fixed in Emacs 27. Just setting `server-name` causes Emacs to fail. Setting it in `emacs-startup-hook`, which is run after after handling the command line arguments, i.e., starting the server, works.

**Comment by tarsius** [comment]
Thanks for letting us know!
