### ISSUE TITLE
with-editor broken for term-mode

### ISSUE THREAD

**Issue by soppera** [magit/with-editor#70]
`with-editor-export-editor` does not work with `term` command.

Steps to reproduce:

1. `M-x term` (use `/bin/bash` shell)
2. `C-c M-x with-editor-export-editor` (use default `EDITOR` variable)
3. `cd <some git repository with staged modifications>`
4. `git commit`

This will fail to edit the proper description file for the Git `commit` command and instead open a non existing file.

This issue does not reproduce with `M-x shell` or `M-x eshell` though; it only affects `M-x term`.

I reproduced this issue with both Linux and Cygwin with the `with-editor` MELPA package version  `20200102.2147`. It was working fine with version `20180618.1602` (see below why). 

The issue is due to the result of the step 2. above. When running `M-x with-editor-export-editor` we can see in the terminal:
```
$  export EDITOR=sh\ -c\ \'echo\ \"WITH-EDITOR\:\ \$\$\ OPEN\ \ IN\ \$\(pwd\)\"\;\ sleep\ 604800\ \&\ sleep\=\$\!\;\ trap\ \"kill\ \$sleep\;\ exit\ 0\"\ USR1\;\ trap\ \"kill\ \$sleep\;\ exit\ 1\"\ USR2\;\ wait\ \$sleep\'
```

If I dump the `EDITOR` variable that results of this command I see:
```
$ echo $EDITOR
sh -c 'echo "WITH-EDITOR: $$ OPEN IN $(pwd)"; sleep 604800 & sleep=$!; trap "kill $sleep; exit 0" USR1; trap "kill $sleep; exit 1" USR2; wait $sleep'
```

Please note that this string misses the argument in the echo command between `OPEN` and `IN`.

For the sake of comparison in `M-x shell` we have:
```
$ echo $EDITOR
sh -c 'echo "WITH-EDITOR: $$ OPEN $0^_ IN $(pwd)"; sleep 604800 & sleep=$!; trap "kill $sleep; exit 0" USR1; trap "kill $sleep; exit 1" USR2; wait $sleep'
```

We can see that this time we have `... OPEN $0^_ IN...`. The issue is the character `^_` (the escaped representation in Emacs of \x1f). This character, when passed to the `term` process, deletes the previous characters, `$0`, and does not print itself. As a consequence the `EDITOR` script does not print the file name to edit and this break `with-editor`.

This error did not exist in version `20180618.1602` of the package because this version only used `OPEN xxx`; it did not include the `IN` prefix and the needed separator.

I solved this issue by using the escaped sequence for this character instead of writing it directly.
So I changed the variable `with-editor-sleeping-editor` to use this value:

``` sh -c 'echo -e "WITH-EDITOR: $$ OPEN $0\\037 IN $(pwd)"; sleep 604800 & sleep=$!; trap "kill $sleep; exit 0" USR1; trap "kill $sleep; exit 1" USR2; wait $sleep' ```

Note that here I use `-e` flag of `echo` and replace `^_` byte by `\\037` (the octal escape of \x1f).
This fixes the issue on both Linux and Cygwin and still works correctly in `M-x shell` and `M-x eshell`.

Attached: [with-editor-debug.txt](https://github.com/magit/with-editor/files/4150419/with-editor-debug.txt)

**Comment by tarsius** [comment]
Very nice bug report. Only the pull-request was missing, but that you have taken care of too now. :grinning:
