### ISSUE TITLE
No editor when commiting using tramp

### ISSUE THREAD

**Issue by mgrachten** [magit/with-editor#72]
When running git commit using magit on a remote repo using tramp, the buffer for editing the commit message does not show up. When I commit on a local repo the buffer does show up (in a new frame).

The buffer `magit-process: repo` shows the following:

    run git … commit --
    hint: Waiting for your editor to close the file...
    -e WITH-EDITOR: 4706 OPEN /path/to/repo/.git/COMMIT_EDITMSG IN /path/to/repo

The  sign prints as `^_` in emacs.

This happens on emacs 27.0.50, without any initialization. Magit version: 20200208.551, with-editor version: 20200204.1828 (from melpa).

I have observed this behavior since a couple of days. Before that it used to work, although normally the commit edit buffer would not open a new frame. I can't tell whether the behavior started with any particular version update.

**Comment by tarsius** [comment]
Sounds like #71 isn't working out so well. @soppera any suggestion?

**Comment by soppera** [comment]
I did a quick test with both `/sudo:` and `/ssh:` TRAMP paths and did not reproduce the issue.

@mgrachten: what TRAMP method are you using? If you use SSH, can you please check if the `-e` flag is supported by the remote machine?
Can you also try reverting #71 by customizing the `with-editor-sleeping-editor` variable, removing the `-e` flag and replacing "\\037" by `C-x RET 1f`?

@tarsius: an alternative to my fix could be to make the first `sh` command do the escaping of this character inside the `echo` parameter. I am not sure it's doable though.

**Comment by soppera** [comment]
One thing I don't understand in the log above is that with have both the `-e` printed out but the escaping actually occurred since it seems `\\037` have been correctly converted. Note sure to understand why that would happen and why echo would print out its flags.

**Comment by soppera** [comment]
Actually: https://stackoverflow.com/questions/4435853/echo-outputs-e-parameter-in-bash-scripts-how-can-i-prevent-this.

It seems that the `-e` flag is not supported by all shells. But the escaping occurs when `-e` is not supported.

**Comment by mgrachten** [comment]
> I did a quick test with both `/sudo:` and `/ssh:` TRAMP paths and did not reproduce the issue.
> 
> @mgrachten: what TRAMP method are you using? If you use SSH, can you please check if the `-e` flag is supported by the remote machine?
> Can you also try reverting #71 by customizing the `with-editor-sleeping-editor` variable, removing the `-e` flag and replacing "\037" by `C-x RET 1f`?

Yes, that fixes the issue.

**Comment by mgrachten** [comment]
> Actually: https://stackoverflow.com/questions/4435853/echo-outputs-e-parameter-in-bash-scripts-how-can-i-prevent-this.
> 
> It seems that the `-e` flag is not supported by all shells. But the escaping occurs when `-e` is not supported.

That seems to be the culprit. `echo` in `sh` (dash on ubuntu/debian systems) prints the -e. If I change  `with-editor-sleeping-editor` to use `bash` instead of `sh` (but keeping -e and \037) the problem is also solved.

**Comment by tarsius** [comment]
Is there some other character that would be safe(r) to use as separator?

**Comment by soppera** [comment]
I am looking at https://stackoverflow.com/questions/39534828/echo-e-not-working-in-su-c-command; it seems printf may be useful here.

Can you do `sh --version` to identify the shell that does not support `echo -e`?

**Comment by soppera** [comment]
@tarsius: the usual separator for files is \x00; I don't know if it works for `M-x term` though.

**Comment by mgrachten** [comment]
Finally, replacing `echo -e` by `printf` while using `sh` also solves the issue. This is problably the best solution, given that POSIX recommends using `printf` instead of `echo`. https://askubuntu.com/questions/537984/difference-between-echo-e-string-and-echo-string

**Comment by soppera** [comment]
I did the test for `M-x term` on my Linux box with `printf` and it seems to work.

**Comment by mgrachten** [comment]
Ok, with `printf` instead of `echo -e` this issue can be closed as far as I'm concerned. Thanks!

**Comment by soppera** [comment]
> @tarsius: the usual separator for files is \x00; I don't know if it works for `M-x term` though.

Actually \x00 is not a good idea here since shells are using null terminated strings.
So I think sticking to \x1f but using `printf` is still the better option.
The only downside is that it does not supported editing files containing this byte in their path.

An alternative would be to quote the file and directory paths (not sure how to do that in shell though, maybe `%q` of `printf` can be used here) so that we don't need a separator character.

**Comment by lguez** [comment]
Hello. I have this issue, with a recent version of with-editor. I run Emacs  27.1 on LinuxMint 21.3. The package list of Emacs says I have with-editor version 20240101.2226. I access a remote repository with tramp, through ssh. The commit does not work. The magit-process window says:
```
run git … commit --
hint: Waiting for your editor to close the file...

WITH-EDITOR: 2479125 OPEN /gpfs7kw/linkhome/.../Jumble/.git/COMMIT_EDITMSG^_^_ IN /linkhome/.../Jumble
```
There is no problem when I run magit on a local repository.
