### ISSUE TITLE
No advice for make-process in Emacs 27

### ISSUE THREAD

**Issue by phst** [magit/with-editor#75]
In Emacs 27, `make-process` has a `:file-handler` argument to enable file name handlers. Tramp has already implemented support for it. However, `with-editor` now also needs an advice for `make-process`, similar to the `start-file-process` advice, to make the following work under Emacs 27:

```elisp
(let ((default-directory "/ssh:remote-host:/"))
  (with-editor
    (make-process :file-handler t :buffer "*temp*"
		  :name "" :command '("bash" "-c" "eval $EDITOR /tmp/test"))))
```

**Comment by tarsius** [comment]
Could you implement that please? With a good commit message.

**Comment by phst** [comment]
Yes, I can try :)
