### ISSUE TITLE
Do not add-hook to term-mode-hook

### ISSUE THREAD

**Issue by sfllaw** [magit/with-editor#8]
The documentation has instructions to:

    (add-hook 'term-mode-hook   'with-editor-export-editor)

However, that fires too early. `term-mode-hook` runs _before_ the process is created. We want:

    (add-hook 'term-exec-hook   'with-editor-export-editor)

**Comment by tarsius** [comment]
> However, that fires too early.

I can confirm that this *now* (Emacs 25.1 ish) is the case, but I think this wasn't the case earlier. It appears that `term-mode-hook` is now run earlier than it used to. We don't want to use `term-exec-hook` to run it before every command; running `export EDITOR=...` once is enough, but of course the shell process already has to exist.

**Comment by sfllaw** [comment]
@tarsius, I think that `term-exec-hook` only runs after every `term-exec`.

Which makes sense. If you kill the term buffer's process and then `term-exec` a new shell, you want the `export EDITOR=...` to run again.

**Comment by tarsius** [comment]
You are right; I misunderstood `term-exec-hook`'s doc-string. Thanks!
