### ISSUE TITLE
*ERROR*: Wrong type argument: stringp, nil

### ISSUE THREAD

**Issue by psanford** [magit/with-editor#80]
Using magit on nixos I get the following error when doing a magit commit amend:

```
  1 git … commit --amend
hint: Waiting for your editor to close the file...
Waiting for Emacs...
*ERROR*: Wrong type argument: stringp, nil
error: There was a problem with the editor '/nix/store/xjvxpwbd7xl50avs331nj4amxs9nv6zg-emacs-26.3/bin/emacsclient --socket-name=/tmp/emacs1000/server'.
Please supply the message using either -m or -F option.
```

`with-editor-debug` shows:
```
with-editor: /home/psanford/.emacs.d/elpa/with-editor-20200720.2014/with-editor.el
emacs: /nix/store/w3603mj256dhrjc9l3rzmcsbrhyr3xdp-system-path/bin/emacs (26.3)
system:
  system-type: gnu/linux
  system-configuration: x86_64-pc-linux-gnu
  system-configuration-options: --prefix=/nix/store/xjvxpwbd7xl50avs331nj4amxs9nv6zg-emacs-26.3 --disable-build-details --with-modules --with-x-toolkit=gtk3 --with-xft CFLAGS=-DMAC_OS_X_VERSION_MAX_ALLOWED=101200
server:
  server-running-p: t
  server-process: #<process server>
  server-use-tcp: nil
  server-name: server
  server-socket-dir: /tmp/emacs1000
    server
  server-auth-dir: ~/.emacs.d/server/
    WARNING: not an accessible directory
with-editor-emacsclient-executable:
 value:   /nix/store/xjvxpwbd7xl50avs331nj4amxs9nv6zg-emacs-26.3/bin/emacsclient (26.3)
 default: /nix/store/xjvxpwbd7xl50avs331nj4amxs9nv6zg-emacs-26.3/bin/emacsclient (26.3)
 funcall: /nix/store/xjvxpwbd7xl50avs331nj4amxs9nv6zg-emacs-26.3/bin/emacsclient (26.3)
path:
  $PATH: "/home/psanford/lib/gotools:/home/psanford/bin:/home/psanford/lib/gotools:/home/psanford/bin:/run/wrappers/bin:/home/psanford/.nix-profile/bin:/etc/profiles/per-user/psanford/bin:/nix/var/nix/profiles/default/bin:/run/current-system/sw/bin"
  exec-path: (/home/psanford/lib/gotools /home/psanford/bin /home/psanford/lib/gotools /home/psanford/bin /run/wrappers/bin /home/psanford/.nix-profile/bin /etc/profiles/per-user/psanford/bin /nix/var/nix/profiles/default/bin /run/current-system/sw/bin /nix/store/xjvxpwbd7xl50avs331nj4amxs9nv6zg-emacs-26.3/libexec/emacs/26.3/x86_64-pc-linux-gnu)
  with-editor-emacsclient-path:
    /nix/store/xjvxpwbd7xl50avs331nj4amxs9nv6zg-emacs-26.3/bin (t)
      /nix/store/xjvxpwbd7xl50avs331nj4amxs9nv6zg-emacs-26.3/bin/.emacsclient-wrapped (26.3)
      /nix/store/xjvxpwbd7xl50avs331nj4amxs9nv6zg-emacs-26.3/bin/emacsclient (26.3)
    /nix/store/w3603mj256dhrjc9l3rzmcsbrhyr3xdp-system-path/bin (t)
      /nix/store/w3603mj256dhrjc9l3rzmcsbrhyr3xdp-system-path/bin/emacsclient (26.3)
    /home/psanford/lib/gotools (t)
    /home/psanford/bin (t)
      /home/psanford/bin/.pms-emacsclient.swp (nil)
      /home/psanford/bin/pms-emacsclient (26.3)
    /run/wrappers/bin (/run/wrappers/wrappers.DtGB4qMIEN)
    /home/psanford/.nix-profile/bin (nil)
    /etc/profiles/per-user/psanford/bin (nil)
    /nix/var/nix/profiles/default/bin (/nix/store/3nb52k2k0wrbl2z4a856yfp3hxwa9mhz-vim-8.2.0013/bin)
    /run/current-system/sw/bin (t)
      /run/current-system/sw/bin/emacsclient (26.3)
    /nix/store/xjvxpwbd7xl50avs331nj4amxs9nv6zg-emacs-26.3/libexec/emacs/26.3/x86_64-pc-linux-gnu (t)
```

Using `execsnoop` I see the emacsclient getting executed like so:
```
emacsclient      12622  12621    0 /nix/store/xjvxpwbd7xl50avs331nj4amxs9nv6zg-emacs-26.3/bin/emacsclient --socket-name=/tmp/emacs1000/server /tmp/foo/.git/COMMIT_EDITMSG
```

Invoking the above command from the command like works fine. 

(Normally i would `(setq debug-on-error t)` to see the stacktrace of the error in emacs but it looks like either `with-editor` or `magit` is catching the exception which makes it difficult for me to debug further.)

**Comment by npostavs** [comment]
> (Normally i would `(setq debug-on-error t)` to see the stacktrace of the error in emacs but it looks like either `with-editor` or `magit` is catching the exception which makes it difficult for me to debug further.)

Try `(setq debug-on-signal t)`. Although you may hit some false positives with this, in which case press `c` to continue.

**Comment by psanford** [comment]
> Try (setq debug-on-signal t). Although you may hit some false positives with this, in which case press c to continue.

This didn't trigger anything either.

**Comment by tarsius** [comment]
Yes that unfortunately doesn't work here.

Issues like this are kinda frequent actually. It's usually some faulty third-party code that has been added to a with-editor-finish-query-functions, with-editor-pre-finish-hook, with-editor-pre-cancel-hook, git-commit-setup-hook. Try removing such functions to figure out which one is to blame.

---

Is there a macro like `with-demoted-errors` that still errors but adds a prefix that could help with debugging. We already demote errors while running `git-commit-setup-hook` but probably shouldn't go as far for the other hooks.

**Comment by npostavs** [comment]
Oh, I somehow remembered `debug-on-signal` working in some previous cases like this one. If it doesn't, I think that means the error is occurring in a context where the debugger is suppressed via `inhibit-debugger` (errors during redisplay are one example of this), rather than magit or with-editor catching the error.

**Comment by tarsius** [comment]
> Oh, I somehow remembered `debug-on-signal` working in some previous cases like this one.

Maybe it does sometimes, I am not sure, but when we suggest `debug-on-signal` in this context, then we should mention that it might not work. Especially if op said they had already done that. ;P
