### ISSUE TITLE
Feature Request: vterm support

### ISSUE THREAD

**Issue by dpassen** [magit/with-editor#81]
[vterm](https://github.com/akermu/emacs-libvterm) is a popular terminal emulator and alternative to eshell, shell, and term. It would be nice to have with-editor working from within.

**Comment by tarsius** [comment]
I was planning to take `vterm` for a spin for a long time. Maybe this requests is the final nudge needed.

I quickly ran into my first issue and hope you can help with that (and maybe subsequent issues). Of course I immediately ran emacs inside emacs and now I cannot figure out how to quit just the inner emacs--the outer emacs wants to act on the `C-x C-c`. I would expect there to be some "pass through mode" but cannot locate it.

**Comment by dpassen** [comment]
Not as far as I can tell. All the more reason for integration?
